#! /usr/bin/env node
'use strict';

/* jshint node: true */

console.time('Total execution time');
process.on('uncaughtException', fail);

var async   = require('async');
var config  = require('../config');
var dropbox = require('../lib/dropbox-sync');
var tarball = require('../lib/tarball');
var clean   = require('../lib/clean');
var outFile = config.file.file_prefix + 'webroot-' + Date.now();

async.series({
  connect: function (cb) {
    dropbox.connect({
      key: config.dropbox.key,
      secret: config.dropbox.secret
    });

    dropbox.setServerPrefix(config.server);
    dropbox.setDirectory(config.file.directory);

    cb();
  },
  archive: tarball.create.bind(tarball, outFile, config.file.include),
  sync: dropbox.send.bind(dropbox, outFile),
  clean: clean.bind(clean, outFile)
}, function (err, args) {
  if (err) return fail(err);

  console.log('The file system backup has been completed successfully.\n');
  console.log('Directories backed up: %s\n', config.file.include.join(', '));
  console.timeEnd('Total execution time');
  console.log('\nThe backup file has been saved to your Dropbox: %s (%s)', args.sync.path, args.sync.humanSize);
  process.exit(0);
});

function fail (err) {
  clean(outFile);

  console.error('The file system backup job has encountered a fatal error and could not continue.\n');
  console.error(err);

  process.exit(1);
}
